name: CiCd Test Demo
on: [push]
jobs:
  ts-lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: |
          echo "Starting the linting test..."
          npm run lint
  unit-test:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs: ts-lint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: |
          echo "Starting unit tests..."
          npm run test
  build-test:
    name: Build Testing
    runs-on: ubuntu-latest
    needs: [ts-lint, unit-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: |
          echo "Starting build production..."
          npm run build
